#!/usr/bin/env bash
# Deploy psychopomp-registry + psychopomp-escrow LEZ programs to the
# psychopomp sequencer. Requires:
#   - sequencer already running (./scripts/run-psychopomp-sequencer.sh in another term)
#   - LEZ guest ELFs built (./scripts/build-lez-guests.sh first)
#   - wallet config at $NSSA_WALLET_HOME_DIR (set below)
#
# Captures the two ProgramIds into deployment-config.toml.

set -euo pipefail
HERE="$(cd "$(dirname "$0")/.." && pwd)"
LEZ="${LEZ_HOME:-$HOME/lez}"
if [[ ! -d "$LEZ" ]]; then
    echo "LEZ checkout not found at $LEZ" >&2
    echo "Set LEZ_HOME=/path/to/your/lez checkout (see docs/PHASE1-onchain.md)." >&2
    exit 1
fi
WALLET="$LEZ/target/release/wallet"
SPEL="$LEZ/target/release/spel"
REG_ELF="$HERE/Phase1-onchain/psychopomp-registry/methods/guest/target/riscv32im-risc0-zkvm-elf/docker/psychopomp_registry.bin"
ESC_ELF="$HERE/Phase1-onchain/psychopomp-escrow/methods/guest/target/riscv32im-risc0-zkvm-elf/docker/psychopomp_escrow.bin"
OUT="$HERE/sequencer-state/deployment-config.toml"

export NSSA_WALLET_HOME_DIR="$HERE/sequencer-state/wallet"

for f in "$REG_ELF" "$ESC_ELF"; do
    if [[ ! -f "$f" ]]; then
        echo "Missing ELF: $f" >&2
        echo "Run ./scripts/build-lez-guests.sh first." >&2
        exit 1
    fi
done

echo ">> wallet check-health"
"$WALLET" check-health

echo ">> inspecting program ids"
REG_ID=$("$SPEL" inspect "$REG_ELF" 2>&1 | grep -oE '[0-9a-f]{64}' | head -1)
ESC_ID=$("$SPEL" inspect "$ESC_ELF" 2>&1 | grep -oE '[0-9a-f]{64}' | head -1)
echo "  registry IMAGE_ID: $REG_ID"
echo "  escrow   IMAGE_ID: $ESC_ID"

echo ">> deploying registry"
"$WALLET" deploy-program "$REG_ELF"

echo ">> deploying escrow"
"$WALLET" deploy-program "$ESC_ELF"

# Wait for sequencer to register and re-query.
sleep 3
echo ">> programs registered on sequencer:"
cargo run --release --quiet --manifest-path "$HERE/Cargo.toml" \
    -p psychopomp-chain --example list-programs 2>/dev/null || \
    curl -s -X POST -H 'content-type: application/json' \
        --data '{"jsonrpc":"2.0","method":"getProgramIds","params":[],"id":1}' \
        http://127.0.0.1:3050/

cat > "$OUT" <<EOF
# Generated by deploy-onchain.sh - psychopomp deployment manifest.
sequencer = "http://127.0.0.1:3050/"

[programs.registry]
image_id_hex = "$REG_ID"

[programs.escrow]
image_id_hex = "$ESC_ID"
EOF
echo ">> wrote $OUT"
